---
services:
  kafka:
    image: apache/kafka:latest # Use the official Apache Kafka image
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KAFKA_NODE_ID: Unique ID for this Kafka broker (required for KRaft)
      KAFKA_NODE_ID: 1
      
      # KAFKA_PROCESS_ROLES: Define the roles for this Kafka instance
      # For a single-node development setup, 'controller,broker' is common.
      KAFKA_PROCESS_ROLES: controller,broker
      
      # KAFKA_LISTENERS: Define how Kafka listens for connections
      # CONTROLLER for inter-broker communication/metadata, PLAINTEXT for client connections
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: Map listeners to security protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      
      # KAFKA_CONTROLLER_QUORUM_VOTERS: Defines the KRaft controller quorum
      # For a single node, it's just itself. Format: <node_id>@<hostname>:<port>
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      
      # KAFKA_CONTROLLER_LISTENER_NAMES: Name of the listener for controller communication
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # KAFKA_ADVERTISED_LISTENERS: How clients connect to the broker
      # Ensure localhost:9092 is advertised for your Node.js app
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: Optional, enable/disable auto topic creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
